import pandas as pd
import numpy as np
import talib
from typing import Dict, Optional, Tuple
from dataclasses import dataclass


@dataclass
class StrategySignal:
    """Signal generated by the strategy"""
    signal_type: Optional[str]  # "long", "short", or None
    entry_price: float
    stop_loss: float
    take_profit: float
    vwap: float
    upper_band: float
    lower_band: float
    atr: float
    rsi: float
    confidence: float = 1.0


class VWAPBandsScalp:
    """
    VWAP Bands Scalping Strategy
    
    Entry Logic:
    - Long: price < lower_band AND RSI < 35
    - Short: price > upper_band AND RSI > 65
    
    Exit Logic:
    - Target: 2:1 Risk/Reward based on ATR
    - Stop Loss: 1 ATR from entry
    - Take Profit: 2 ATR from entry
    - Alternative exit: price touches VWAP mean
    """
    
    def __init__(
        self,
        atr_length: int = 14,
        vwap_length: int = 30,
        band_multiplier: float = 2.0,
        rsi_length: int = 7,
        rsi_long_threshold: float = 35.0,
        rsi_short_threshold: float = 65.0
    ):
        self.atr_length = atr_length
        self.vwap_length = vwap_length
        self.band_multiplier = band_multiplier
        self.rsi_length = rsi_length
        self.rsi_long_threshold = rsi_long_threshold
        self.rsi_short_threshold = rsi_short_threshold
    
    def calculate_vwap(self, df: pd.DataFrame) -> pd.Series:
        """Calculate VWAP (Volume Weighted Average Price)"""
        typical_price = (df['high'] + df['low'] + df['close']) / 3.0
        volume = df['volume'].replace(0, 1e-9)  # Avoid division by zero
        
        pv = typical_price * volume
        cum_pv = pv.cumsum()
        cum_v = volume.cumsum()
        
        vwap = (cum_pv / cum_v).fillna(method='ffill')
        return vwap
    
    def calculate_atr(self, df: pd.DataFrame) -> pd.Series:
        """Calculate ATR (Average True Range)"""
        high = df['high'].values
        low = df['low'].values
        close = df['close'].values
        
        atr = talib.ATR(high, low, close, timeperiod=self.atr_length)
        return pd.Series(atr, index=df.index)
    
    def calculate_rsi(self, df: pd.DataFrame) -> pd.Series:
        """Calculate RSI (Relative Strength Index)"""
        close = df['close'].values
        rsi = talib.RSI(close, timeperiod=self.rsi_length)
        return pd.Series(rsi, index=df.index)
    
    def calculate_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        """Calculate all technical indicators"""
        df = df.copy()
        
        # VWAP
        df['vwap'] = self.calculate_vwap(df)
        
        # Smooth VWAP for bands
        df['vwap_smooth'] = df['vwap'].rolling(
            window=self.vwap_length,
            min_periods=self.vwap_length // 2
        ).mean()
        
        # ATR for volatility bands
        df['atr'] = self.calculate_atr(df)
        
        # VWAP Bands
        df['upper_band'] = df['vwap_smooth'] + (self.band_multiplier * df['atr'])
        df['lower_band'] = df['vwap_smooth'] - (self.band_multiplier * df['atr'])
        
        # RSI
        df['rsi'] = self.calculate_rsi(df)
        
        return df
    
    def generate_signal(self, df: pd.DataFrame) -> StrategySignal:
        """
        Generate trading signal from OHLCV data
        
        Args:
            df: DataFrame with OHLCV data (must have at least 200 candles)
        
        Returns:
            StrategySignal object
        """
        # Calculate indicators
        df = self.calculate_indicators(df)
        
        # Get latest values
        latest = df.iloc[-1]
        close = latest['close']
        vwap = latest['vwap_smooth']
        upper = latest['upper_band']
        lower = latest['lower_band']
        atr = latest['atr']
        rsi = latest['rsi']
        
        # Check for NaN values
        if pd.isna([vwap, upper, lower, atr, rsi]).any():
            return StrategySignal(
                signal_type=None,
                entry_price=close,
                stop_loss=close,
                take_profit=close,
                vwap=vwap if not pd.isna(vwap) else close,
                upper_band=upper if not pd.isna(upper) else close,
                lower_band=lower if not pd.isna(lower) else close,
                atr=atr if not pd.isna(atr) else 0,
                rsi=rsi if not pd.isna(rsi) else 50,
                confidence=0.0
            )
        
        signal_type = None
        stop_loss = close
        take_profit = close
        
        # Long signal: price below lower band and RSI oversold
        if close < lower and rsi < self.rsi_long_threshold:
            signal_type = "long"
            stop_loss = close - atr
            take_profit = close + (2 * atr)
        
        # Short signal: price above upper band and RSI overbought
        elif close > upper and rsi > self.rsi_short_threshold:
            signal_type = "short"
            stop_loss = close + atr
            take_profit = close - (2 * atr)
        
        return StrategySignal(
            signal_type=signal_type,
            entry_price=close,
            stop_loss=stop_loss,
            take_profit=take_profit,
            vwap=vwap,
            upper_band=upper,
            lower_band=lower,
            atr=atr,
            rsi=rsi,
            confidence=1.0 if signal_type else 0.0
        )
    
    def should_exit(
        self,
        entry_price: float,
        current_price: float,
        stop_loss: float,
        take_profit: float,
        vwap: float,
        is_long: bool
    ) -> Tuple[bool, str]:
        """
        Check if position should be exited
        
        Returns:
            (should_exit, reason)
        """
        if is_long:
            # Stop loss hit
            if current_price <= stop_loss:
                return True, "stop_loss"
            
            # Take profit hit
            if current_price >= take_profit:
                return True, "take_profit"
            
            # Price touched VWAP mean (alternative exit)
            if current_price >= vwap and current_price > entry_price:
                return True, "vwap_mean"
        
        else:  # Short position
            # Stop loss hit
            if current_price >= stop_loss:
                return True, "stop_loss"
            
            # Take profit hit
            if current_price <= take_profit:
                return True, "take_profit"
            
            # Price touched VWAP mean (alternative exit)
            if current_price <= vwap and current_price < entry_price:
                return True, "vwap_mean"
        
        return False, ""
